---
title: "Structural MRI Principal Component Analysis"
author: "Ian Douglas"
date: "11/12/2019"
output:
  html_document:
    code_folding: "hide" # code folding added for this one.
    number_sections: yes
    toc: yes
    df_print: paged
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: yes
    df_print: paged
---
# PCA projection plots
```{r, echo=FALSE, results='hide', message=FALSE}
library(tidyverse)
```

```{r, echo=FALSE, results='hide',message=FALSE}
strPCA.noWBV <- readRDS("./results/PCA/strPCAobj_noWBV.rds")
lblStrData <- readRDS("~/DANL/SB/data/processed/structuralLabelled.rds")
lblStrPCArawData.noWBV = na.omit(lblStrData[c(1,6:26)]) # (no whole brain vol)
CoLoRs.noWBV = 1+(as.numeric(as.factor(
  left_join(lblStrPCArawData.noWBV["IDENT_SUBID"],
            lblStrData[c("IDENT_SUBID","GROUP")])$GROUP))^2)
```

```{r}
plot(strPCA.noWBV$x[,1],strPCA.noWBV$x[,2], #the PCA object (`x` refers to the transformed data)
     col = CoLoRs.noWBV, # custom color pallette based on grouping variable
     xlab = 'dimension 1', ylab = 'dimension 2', pch = 16,
     main = "Data Projected onto PC1 and PC2\nwithout Brain Vol.")
legend('topright', legend = c("PI","COMP"), fill = c(5,2))

plot(strPCA.noWBV$x[,1],strPCA.noWBV$x[,3], 
     col = CoLoRs.noWBV, # custom color pallette based on grouping variable
     xlab = 'dimension 1', ylab = 'dimension 3', pch = 16,
     main = "Data Projected onto PC1 and PC3\nwithout Brain Vol.")
legend('topright', legend = c("PI","COMP"), fill = c(5,2))

plot(strPCA.noWBV$x[,2],strPCA.noWBV$x[,3], 
     col = CoLoRs.noWBV, # custom color pallette based on grouping variable
     xlab = 'dimension 2', ylab = 'dimension 3', pch = 16,
     main = "Data Projected onto PC2 and PC3\nwithout Brain Vol.")
legend('topright', legend = c("PI","COMP"), fill = c(5,2))
```
