---
title: "02_functionalConnectivity"
author: "Ian Douglas"
date: "10/23/2019"
output:
  html_document:
    number_sections: yes
    toc: yes
    df_print: paged
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: yes
    df_print: paged
---
```{r}
require(tidyverse)
library(TSdist) # not available for R vesion 3.6.1! (running script in 3.5.3)
```

# 1. Subject ID Key
```{r}
lblDataToPull = readRDS('../data/labels/wave1Labels.rds')
```

# 2. Read in subjects from the wave 1 key, compute funcional connectivity
```{r}
# initialize empty objects
masterFuncCorBySubj = vector(mode = "list")
masterFuncDissBySubj = vector(mode = "list")
any_zv = c() 

for (i in lblDataToPull$IDENT_SUBID) {
  folder = as.character(
    lblDataToPull[lblDataToPull$IDENT_SUBID==i, "folder_name"])
  
  #read in the i-th participant's time series data and remove custom regions:
  TS = readRDS(
    paste0('../data/raw/raw_TS_by_subj/',folder,'/raw.rds'))[,-1:-8]
  
  # run the check for NA, which are produced by variables with SD = 0
  if (any(is.na(cor(TS)))) {
    any_zv = c(any_zv, i) # if so, keep track of the subject ID.
  } else 
    if (all(!is.na(cor(TS)))) {
      # Compute correlation and dissimiliarity matrices between regions.
      # The dissimiliarity transforms the pearson correlation to approach
      # infinity as the correlation reaches -1, and 0 as r approaches 1.
      CORR = cor(TS)
      DISS = as.matrix(TSDatabaseDistances(t(TS), distance = "cor"))
    
      # extract the lower triangle (between region connectivity)
      lt.CORR = as.vector(CORR)[which(lower.tri(CORR, diag = FALSE))]
      lt.DISS = as.vector(DISS)[which(lower.tri(DISS, diag = FALSE))]
    
      # Extract the same combination of variable names
      region_names = names(TS)
      allCombos = paste0(rep(region_names, times = length(TS)), ".X.",
                       rep(region_names, each = length(TS)))
      retainedCombosCorr = allCombos[which(lower.tri(CORR, diag = FALSE))]
      retainedCombosDiss = allCombos[which(lower.tri(DISS, diag = FALSE))]
    
      # Format data for outputting in lists
      corrDf = data.frame("correlation" = lt.CORR)
      rownames(corrDf) = retainedCombosCorr
      dissDf = data.frame("dissimiliarity" = lt.DISS)
      rownames(dissDf) = retainedCombosDiss
    
      # Input the data into the output lists
      masterFuncCorBySubj[[i]] = corrDf
      masterFuncDissBySubj[[i]] = dissDf
    }
}

```

# 3. Create functional connectivity data frames
```{r}
subjCor = names(masterFuncCorBySubj)
subjDiss = names(masterFuncDissBySubj)
for (i in 1:length(masterFuncCorBySubj)) {
  if (i == 1) {data = masterFuncCorBySubj[[i]]} else
    data = cbind(data, masterFuncCorBySubj[[i]])
  if (i == length(masterFuncCorBySubj)) {
    ColNames = rownames(masterFuncDissBySubj[[i]])
    data = as.data.frame(t(data))
    names(data) = ColNames
    data %>% 
      mutate("IDENT_SUBID" = as.character(subjCor)) %>%
      left_join(., lblDataToPull[, c("IDENT_SUBID", "age", "GROUP")]) %>%
      assign("fCor", ., pos = .GlobalEnv)
  }
}

for (i in 1:length(masterFuncDissBySubj)) {
  if (i == 1) {data = masterFuncDissBySubj[[i]]} else
    data = cbind(data, masterFuncDissBySubj[[i]])
  if (i == length(masterFuncDissBySubj)) {
    ColNames = rownames(masterFuncDissBySubj[[i]])
    data = as.data.frame(t(data))
    names(data) = ColNames
    data %>% 
      mutate("IDENT_SUBID" = as.character(subjDiss)) %>%
      left_join(., lblDataToPull[, c("IDENT_SUBID", "age", "GROUP")]) %>%
      assign("fDiss", ., pos = .GlobalEnv)
  }
}

saveRDS(fCor,"~/DANL/SB/data/processed/labelledFCor.rds")
saveRDS(fDiss,"~/DANL/SB/data/processed/labelledFDiss.rds")
```

