---
title: "netBag [bagged neural net]"
author: "Ian Douglas"
date: "10/7/2019"
output:
  html_document:
    number_sections: yes
    toc: yes
    df_print: paged
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: yes
    df_print: paged
---
```{r}
require(tidyverse)
require(caret)
require(nnet)
require(effsize)
require(hybridEnsemble)
require(MLmetrics)
```

# read in raw structural data
```{r}
brainStructure = readRDS("../data/processed/wave1structuralDataLABELLED.rds")
# delete any variables with zero variance
brainStructure = brainStructure[
  ,c(rep(TRUE,times = 10), !sapply(brainStructure[11:64], var) == 0)]
# read in some target variables
load( # the .Rdata file is named "monster_SB"
  '../data/raw/3_ALL_long_cort_symptoms_brain_structure_function_epi_ages4-19_2019-05-15.Rdata'
)
# filter the data by the subjects contained in brainstructure
masterDataFiltered = monster_SB[monster_SB$SUBJECTID_long %in% brainStructure$SUBJECTID_long,]
```

#check out some std. mean differences
```{r}
effsizeDF = data.frame(stringsAsFactors = FALSE,
  var=names(brainStructure[11:69]),
  effsize = sapply(brainStructure[11:69], 
                   function(x) cohen.d( d = x, f =  brainStructure$GROUP)$estimate)) %>%
  arrange(desc(effsize))
```



# ensemble model of neural nets
```{r}
# use the top 35, for which there was a significant mean difference
netData = brainStructure[,c("SUBJECTID_long","GROUP","age", as.character(effsizeDF$var)[1:35])]
classNetData = select(netData, -age, -SUBJECTID_long) %>%
  mutate_at(vars("GROUP"),as.factor) %>%
  select(GROUP, everything())
classNetData.scl = classNetData %>% mutate_at(-1, scale) %>%
  mutate_at(1, function(x) ifelse(x == "PI", 1, 0)) %>%
  mutate_at(1, as.numeric)
# train-test split
CVnet = function(data) {
  factory = is.factor(data$GROUP)
  CV1 = list()
  for (i in 1:10) {
    set.seed(i)
    if (factory) {
    train.ind <<- c(
      sample(grep("PI", data$GROUP), size = round(length(grep("PI", data$GROUP))*.7)),
      sample(grep("COMP", data$GROUP), size = length(round(length(grep("PI", data$GROUP))*.7)))
    )
    }
    if (!factory) {
    train.ind <<- c(
      sample(which(data$GROUP == 1), size = round(length(which(data$GROUP == 1))*.7)),
      sample(which(data$GROUP == 0), size = round(length(which(data$GROUP == 1))*.7))
    )
    }
    train <- data[train.ind, ]
    test = data[-train.ind, ]
    #fit nnet
    fit = neuralnet(GROUP ~ ., data = train, hidden = c(16, 8, 2, 1))
    if (factory) {
    CV1[[i]] = list("preds"=predict(fit, newdata = test,type="class"),
                    "actual"= as.character(test$GROUP))
    }
    if (!factory) {
    CV1[[i]] = list("preds"=predict(fit, newdata = test),
                    "actual"= test$GROUP)
    }
  }
  #CV1 = mean(CV1)
  return(CV1)
}

CVnet.fit = CVnet(data = classNetData.scl)
#RMSE across all:
mean(
  sapply(lapply(CVnet.fit, function(x) apply(cbind(x[[1]], x[[2]]), 1, function(z)
    (z[1]-z[2])^2)), function(Y) sqrt(mean(Y)))
)
```




